<script setup>
import { computed, onMounted, onUnmounted, ref, watch } from 'vue'
import './dataManager.css'

const ANCIENT_QUALITY_CHOICES = [
  { quality_id: 'ancient_legendary_gold', quality_name: '上古传说', quality_rank: 3.5, max_enhancement_level: 12, has_special_roll_rule: 1, notes: '上古前缀；强化上限与主词条上限沿用传说品质。' },
  { quality_id: 'ancient_mythic_red', quality_name: '上古神话', quality_rank: 4.5, max_enhancement_level: 16, has_special_roll_rule: 1, notes: '上古前缀；强化上限与主词条上限沿用神话品质。' },
]
const BASE_QUALITY_IDS = new Set(['rare_blue', 'epic_purple', 'legendary_gold', 'mythic_red'])
const setsOnly = ref(localStorage.getItem('eaia-sets-only') === '1')
watch(setsOnly, value => localStorage.setItem('eaia-sets-only', value ? '1' : '0'))

function normalizedEquipmentPayload(payload) {
  const root = { ...payload }, wrapped = root.values && typeof root.values === 'object'
  const values = { ...(wrapped ? root.values : root) }
  if (values.quality_id === 'ancient_legendary_gold') { values.quality_id = 'legendary_gold'; values.is_ancient = true }
  else if (values.quality_id === 'ancient_mythic_red') { values.quality_id = 'mythic_red'; values.is_ancient = true }
  else if (BASE_QUALITY_IDS.has(values.quality_id)) values.is_ancient = false
  if (Array.isArray(values.stats)) values.stats = values.stats.map((stat, index) => ({ ...stat, stat_type: stat?.stat_type ? String(stat.stat_type).toUpperCase() : stat?.stat_type, is_unlocked: index === 0 || (stat?.stat_value !== null && stat?.stat_value !== undefined && stat?.stat_value !== '') }))
  if (wrapped) { root.values = values; return root }
  return values
}
function augmentedCatalog(data) {
  const result = { ...data, gear_qualities: [...(data.gear_qualities || [])] }
  for (const quality of ANCIENT_QUALITY_CHOICES) if (!result.gear_qualities.some(row => row.quality_id === quality.quality_id)) result.gear_qualities.push(quality)
  result.stat_definitions = (data.stat_definitions || []).map(row => ({ ...row, stat_type: row.stat_type ? String(row.stat_type).toUpperCase() : row.stat_type }))
  return result
}
function replacedJsonResponse(response, payload) {
  const headers = new Headers(response.headers)
  headers.set('Content-Type', 'application/json; charset=utf-8')
  headers.delete('Content-Length')
  return new Response(JSON.stringify(payload), { status: response.status, statusText: response.statusText, headers })
}
const nativeFetch = window.fetch.bind(window)
const enhancedFetch = async (input, init = {}) => {
  const url = typeof input === 'string' ? input : input?.url || ''
  const method = String(init?.method || 'GET').toUpperCase()
  const hasBody = init?.body && typeof init.body === 'string'
  if (url.includes('/api/manage/equipment') && ['POST', 'PATCH'].includes(method) && hasBody) {
    try { init = { ...init, body: JSON.stringify(normalizedEquipmentPayload(JSON.parse(init.body))) } } catch { /* preserve non-JSON requests */ }
  }
  if (setsOnly.value && url.includes('/api/hero-core/recommend') && hasBody) {
    try { const payload = JSON.parse(init.body); if (!payload.team && !payload.hero_core_ids) init = { ...init, body: JSON.stringify({ ...payload, sets_only: true }) } } catch { /* preserve non-JSON requests */ }
  }
  const response = await nativeFetch(input, init)
  if (response.ok && url.includes('/api/catalog')) {
    try { return replacedJsonResponse(response, augmentedCatalog(await response.clone().json())) } catch { /* preserve response */ }
  }
  return response
}
window.fetch = enhancedFetch

const MODES = new Set(['dictionary','equipment','heroes','recommendation','scanner'])
const hash = ref(window.location.hash)
function syncHash() { hash.value = window.location.hash }
const route = computed(() => hash.value.replace(/^#\/?/, '') || 'heroes')
const view = computed(() => MODES.has(route.value) ? route.value : (route.value === 'simulation' ? 'recommendation' : 'heroes'))
const lang = ref(localStorage.getItem('eaia-language') || 'zh-CN')
const zh = computed(() => lang.value === 'zh-CN')
const busy = ref(false), message = ref(''), error = ref(''), search = ref('')
const TEXT={zh:{brand:'装备与英雄数据库',dictionary:'游戏数据',equipment:'已有装备',heroes:'英雄图鉴',recommendation:'装备推荐',scanner:'识别装备',add:'新增',edit:'编辑',del:'删除',save:'保存',cancel:'取消',search:'搜索',actions:'操作',seq:'序号',slot:'部位',set:'套装',quality:'品质',level:'强化',main:'主词条',sub:'副词条',status:'状态',upload:'上传 HeroCore',template:'下载数据模板',attr:'英雄属性',skills:'技能资料',talents:'天赋/额外机制',core:'HeroCore 可计算',nocore:'暂无 HeroCore',run:'开始配装计算',running:'HeroCore 计算中…',targetDef:'木桩防御',enemies:'目标数量',topK:'结果数量',trials:'精算随机次数',candidate:'每部位候选数',policy:'终结技策略',ed60:'等效60秒伤害',actual60:'实际前60秒',panel:'最终面板',build:'装备组合',delta:'距第一名',connect:'检测连接',start:'开始识别',stop:'停止',progress:'识别进度'},en:{brand:'Equipment & Hero Database',dictionary:'Game Data',equipment:'Inventory',heroes:'Hero Codex',recommendation:'Builds',scanner:'Scanner',add:'Add',edit:'Edit',del:'Delete',save:'Save',cancel:'Cancel',search:'Search',actions:'Actions',seq:'#',slot:'Slot',set:'Set',quality:'Quality',level:'Enhance',main:'Main Stat',sub:'Sub Stats',status:'Status',upload:'Upload HeroCore',template:'Download Template',attr:'Attributes',skills:'Skills',talents:'Talents / Extra Mechanics',core:'HeroCore Ready',nocore:'No HeroCore',run:'Run HeroCore Search',running:'Calculating…',targetDef:'Target DEF',enemies:'Targets',topK:'Results',trials:'Refine Trials',candidate:'Candidates / Slot',policy:'Ultimate Policy',ed60:'Equivalent 60s',actual60:'Actual First 60s',panel:'Final Panel',build:'Equipment Build',delta:'Gap to Best',connect:'Check Connection',start:'Start Scan',stop:'Stop',progress:'Scan Progress'}}
const t=k=>(zh.value?TEXT.zh:TEXT.en)[k]||k
const NAV=computed(()=>[['dictionary',t('dictionary')],['equipment',t('equipment')],['heroes',t('heroes')],['recommendation',t('recommendation')],['scanner',t('scanner')]])
function go(v){location.hash=`#/${v}`}
function toggleLang(){lang.value=zh.value?'en-US':'zh-CN';localStorage.setItem('eaia-language',lang.value)}
async function api(url,opt={}){const r=await fetch(url,opt);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);return d}
function feedback(e=null,m=''){error.value=e?.message||'';message.value=m}
function clone(x){return JSON.parse(JSON.stringify(x))}
function cmp(a,b){const av=a??'',bv=b??'',an=Number(av),bn=Number(bv);if(av!==''&&bv!==''&&Number.isFinite(an)&&Number.isFinite(bn))return an-bn;return String(av).localeCompare(String(bv),zh.value?'zh-CN':'en',{numeric:true,sensitivity:'base'})}
  function sortState(state){return state?.value && typeof state.value==='object'?state.value:state}
  function toggleSort(state,key){const current=sortState(state);const next=current.key===key?{key,direction:current.direction==='asc'?'desc':'asc'}:{key,direction:'asc'};if(state?.value && typeof state.value==='object')state.value=next;else Object.assign(state,next)}
  function mark(state,key){const current=sortState(state);return current?.key!==key?'↕':current.direction==='asc'?'↑':'↓'}
function n(v,d=2){if(v===null||v===undefined||v==='')return '—';const x=Number(v);return Number.isFinite(x)?x.toLocaleString(zh.value?'zh-CN':'en-US',{maximumFractionDigits:d}):String(v)}
function pct(v){return v===null||v===undefined?'—':`${(Number(v)*100).toFixed(1).replace(/\.0$/,'')}%`}

// terminology
const termEntries=ref([]),zhToEn=computed(()=>new Map(termEntries.value.map(x=>[x['zh-CN'],x['en-US']]).filter(x=>x[0]&&x[1]))),enToZh=computed(()=>new Map(termEntries.value.map(x=>[x['en-US'],x['zh-CN']]).filter(x=>x[0]&&x[1])))
function term(v){if(v===null||v===undefined||v==='')return v;const s=String(v);return zh.value?(enToZh.value.get(s)||s):(zhToEn.value.get(s)||s)}
async function loadTerms(){try{const x=await api('/terms.json');termEntries.value=Object.values(x.terms||{})}catch{termEntries.value=[]}}
const STAT={ATK_FLAT:['攻击','ATK'],ATK_PCT:['攻击加成','ATK %'],HP_FLAT:['生命','HP'],HP_PCT:['生命加成','HP %'],DEF_FLAT:['防御','DEF'],DEF_PCT:['防御加成','DEF %'],CRIT_RATE:['暴击率','CRIT Rate'],CRIT_DMG:['暴击伤害','CRIT DMG'],ATK_SPEED:['攻击速度','ATK Speed'],RAGE_REGEN:['怒气回复','Rage Regen'],HEALING_EFFECT:['治疗效果','Healing Effect']}
const SLOT={weapon:['武器','Weapon'],armor:['护甲','Armor'],bracelet:['手镯','Bracelet'],necklace:['项链','Necklace'],ring:['戒指','Ring']}
const QUALITY={mythic_red:['神话','Mythic'],legendary_gold:['传奇','Legendary'],epic_purple:['史诗','Epic'],rare_blue:['稀有','Rare'],ancient_legendary_gold:['上古传说','Ancient Legendary'],ancient_mythic_red:['上古神话','Ancient Mythic']}
const PCT=new Set(['ATK_PCT','HP_PCT','DEF_PCT','CRIT_RATE','CRIT_DMG','RAGE_REGEN','HEALING_EFFECT'])
function pair(map,key,fallback){return map[key]?.[zh.value?0:1]||term(fallback)||key||'—'}
function statName(s){return pair(STAT,s?.stat_type,s?.stat_name)}
function statLabel(s){if(!s)return '—';const raw=s.stat_value??s.estimate_override;if(raw===null||raw===undefined)return statName(s);const x=Number(raw);return `${statName(s)} ${PCT.has(s.stat_type)?`${n(Math.abs(x)<=3?x*100:x,2)}%`:n(x,3)}`}

// generic game data CRUD
const resources=ref([]),resourceId=ref(''),resource=ref({fields:[],primary_keys:[],rows:[]}),resourceSort=ref({key:'',direction:'asc'}),resourceEditor=ref({open:false,mode:'create',form:{},key:{}})
const groups=computed(()=>{const m=new Map();for(const x of resources.value){if(!m.has(x.group))m.set(x.group,[]);m.get(x.group).push(x)}return [...m].map(([name,items])=>({name,items}))})
const resourceMeta=computed(()=>resources.value.find(x=>x.id===resourceId.value)||null),fields=computed(()=>resource.value.fields.filter(x=>!x.hide_in_table).slice(0,9))
const resourceRows=computed(()=>{let rows=resource.value.rows||[];const q=search.value.trim().toLowerCase();if(q)rows=rows.filter(r=>Object.values(r).some(v=>String(v??'').toLowerCase().includes(q)));const s=resourceSort.value;return s.key?[...rows].sort((a,b)=>cmp(a[s.key],b[s.key])*(s.direction==='asc'?1:-1)):rows})
async function loadResource(id=resourceId.value){if(!id)return;busy.value=true;try{resource.value=await api(`/api/manage/resource/${encodeURIComponent(id)}`);resourceId.value=id;resourceSort.value={key:resource.value.primary_keys?.[0]||resource.value.fields?.[0]?.name||'',direction:'asc'}}catch(e){feedback(e)}finally{busy.value=false}}
async function loadDictionary(){busy.value=true;try{resources.value=await api('/api/manage/resources');await loadResource(resourceId.value||'sets')}catch(e){feedback(e);busy.value=false}}
function openResource(mode,row=null){const form=mode==='create'?Object.fromEntries(resource.value.fields.map(f=>[f.name,f.type==='boolean'?false:''])):clone(row);const key={};for(const k of resource.value.primary_keys||[])key[k]=row?.[k];resourceEditor.value={open:true,mode,form,key}}
function resourceValues(){const out={};for(const f of resource.value.fields){let v=resourceEditor.value.form[f.name];if(f.type==='boolean')v=v?1:0;else if(f.type==='number'&&v!==''&&v!=null)v=Number(v);out[f.name]=v}return out}
async function saveResource(){try{const u=`/api/manage/resource/${encodeURIComponent(resourceId.value)}`;const opt={method:resourceEditor.value.mode==='create'?'POST':'PATCH',headers:{'Content-Type':'application/json'}};opt.body=JSON.stringify(resourceEditor.value.mode==='create'?{values:resourceValues()}:{key:resourceEditor.value.key,values:resourceValues()});await api(u,opt);resourceEditor.value.open=false;await loadResource();feedback(null,zh.value?'数据已保存。':'Data saved.')}catch(e){feedback(e)}}
async function delResource(row){if(!confirm(zh.value?'确认删除这条记录？':'Delete this record?'))return;const key={};for(const k of resource.value.primary_keys||[])key[k]=row[k];try{await api(`/api/manage/resource/${encodeURIComponent(resourceId.value)}`,{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({key})});await loadResource()}catch(e){feedback(e)}}
function cell(v,f){if(v===null||v===undefined||v==='')return '—';if(f?.type==='boolean')return Number(v)?(zh.value?'是':'Yes'):(zh.value?'否':'No');return typeof v==='number'?n(v,4):term(v)}

// equipment CRUD
const catalog=ref({}),equipment=ref([]),equipmentSort=ref({key:'_seq',direction:'asc'}),equipmentPage=ref(1),equipmentSearchScope=ref('all'),equipmentEditor=ref({open:false,mode:'create',original:null,seq:null,form:null})
const cat=k=>catalog.value?.[k]||[],slotOptions=computed(()=>cat('equipment_slots')),setOptions=computed(()=>cat('sets').filter(x=>x.active!==0)),qualityOptions=computed(()=>cat('gear_qualities')),statOptions=computed(()=>cat('stat_definitions').filter(x=>x.active!==0)),rollOptions=computed(()=>cat('stat_roll_grades'))
function mainStat(r){return r.stats?.find(x=>Number(x.stat_index)===0||x.stat_source==='main')||null}function subStats(r){const m=mainStat(r);return(r.stats||[]).filter(x=>x!==m).sort((a,b)=>Number(a.stat_index)-Number(b.stat_index))}
function slotName(r){return pair(SLOT,r.slot_id,r.slot_name)}function qualityName(r){return pair(QUALITY,r.quality_id,r.quality_name)}
function eqSortVal(r,k){if(k==='slot')return slotName(r);if(k==='set')return term(r.set_name);if(k==='quality')return qualityName(r);if(k==='main')return statLabel(mainStat(r));if(k==='sub')return subStats(r).map(statLabel).join(' ');return r[k]}
const equipmentSearchOptions=computed(()=>[
  {value:'all',label:zh.value?'全部':'All'},
  {value:'slot',label:t('slot')},
  {value:'set',label:t('set')},
  {value:'equipment',label:zh.value?'装备':'Equipment'},
])
const equipmentRows=computed(()=>{let rows=equipment.value;const q=search.value.trim().toLowerCase();if(q)rows=rows.filter(r=>{const values=equipmentSearchScope.value==='slot'?[slotName(r)]:equipmentSearchScope.value==='set'?[term(r.set_name),r.set_id]:equipmentSearchScope.value==='equipment'?[qualityName(r),r.enhancement_level,r.notes,...(r.stats||[]).flatMap(s=>[statName(s),s.stat_value])]:[slotName(r),term(r.set_name),qualityName(r),r.notes,...(r.stats||[]).flatMap(s=>[statName(s),s.stat_value])];return values.some(v=>String(v??'').toLowerCase().includes(q))});const s=equipmentSort.value;return [...rows].sort((a,b)=>cmp(eqSortVal(a,s.key),eqSortVal(b,s.key))*(s.direction==='asc'?1:-1))})
const equipmentPageCount=computed(()=>Math.max(1,Math.ceil(equipmentRows.value.length/100)))
const equipmentPageRows=computed(()=>equipmentRows.value.slice((equipmentPage.value-1)*100,equipmentPage.value*100))
watch([search,equipmentSort,equipmentSearchScope],()=>{equipmentPage.value=1})
async function loadEquipment(){busy.value=true;equipmentPage.value=1;try{const [c,e]=await Promise.all([api('/api/catalog'),api('/api/manage/equipment')]);catalog.value=c;equipment.value=(e.rows||[]).map((r,i)=>({...r,_seq:i+1}))}catch(e){feedback(e)}finally{busy.value=false}}
function hiddenId(){return `UI_${globalThis.crypto?.randomUUID?crypto.randomUUID().replaceAll('-',''):`${Date.now()}_${Math.random().toString(16).slice(2)}`}`}
function blankStats(){return Array.from({length:5},(_,i)=>({stat_index:i,stat_source:i===0?'main':'sub',stat_type:'',stat_value:'',unlock_level:0,is_unlocked:true,roll_grade_id:'',estimate_override:'',value_confidence:1,notes:''}))}
function blankEquipment(){return{item_id:hiddenId(),slot_id:slotOptions.value[0]?.slot_id||'weapon',set_id:setOptions.value[0]?.set_id||'',quality_id:qualityOptions.value[0]?.quality_id||'mythic_red',enhancement_level:16,locked:false,available:true,is_ancient:false,notes:'',source:'manual',stats:blankStats()}}
function openEquipment(mode,row=null){let form=mode==='create'?blankEquipment():clone(row);if(mode==='edit'){form.locked=!!form.locked;form.available=!!form.available;form.is_ancient=!!form.is_ancient;const m=new Map((form.stats||[]).map(x=>[Number(x.stat_index),x]));form.stats=blankStats().map(x=>({...x,...(m.get(x.stat_index)||{})}))}equipmentEditor.value={open:true,mode,original:row?.item_id||null,seq:row?._seq||null,form}}
function eqPayload(form=equipmentEditor.value.form){const f=clone(form);f.enhancement_level=Number(f.enhancement_level||0);f.stats=(f.stats||[]).map((s,i)=>({...s,stat_index:i,stat_source:i===0?'main':'sub',stat_type:s.stat_type,stat_value:s.stat_value===''?null:Number(s.stat_value),estimate_override:s.estimate_override===''?null:Number(s.estimate_override),unlock_level:Number(s.unlock_level||0),is_unlocked:!!s.is_unlocked,value_confidence:s.value_confidence===''?1:Number(s.value_confidence)}));return f}
async function saveEquipment(){try{const method=equipmentEditor.value.mode==='create'?'POST':'PATCH',body={values:eqPayload()};if(method==='PATCH')body.original_item_id=equipmentEditor.value.original;await api('/api/manage/equipment',{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});equipmentEditor.value.open=false;await loadEquipment();feedback(null,zh.value?'装备已保存。':'Equipment saved.')}catch(e){feedback(e)}}
async function toggleEquipmentAvailability(row){try{const form=clone(row);form.available=!Boolean(row.available);await api('/api/manage/equipment',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({original_item_id:row.item_id,values:eqPayload(form)})});await loadEquipment();feedback(null,zh.value?'配装参与状态已更新。':'Build participation updated.')}catch(e){feedback(e)}}
async function delEquipment(row){if(!confirm(zh.value?`确认删除序号 ${row._seq} 的装备？`:`Delete equipment #${row._seq}?`))return;try{await api('/api/manage/equipment',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({item_id:row.item_id})});await loadEquipment()}catch(e){feedback(e)}}
const seqOf=id=>equipment.value.find(x=>x.item_id===id)?._seq||'?'

// hero codex + upload
const heroPayload=ref({heroes:[],skills:[]}),heroSearch=ref(''),role=ref('all'),faction=ref('all'),heroKey=ref('SUN_WUKONG'),fileInput=ref(null)
function factions(v){return String(v||'').split(/[\/、,，]/).map(x=>x.trim()).filter(Boolean)}
const heroes=computed(()=>heroPayload.value.heroes.map(h=>({...h,skills:heroPayload.value.skills.filter(s=>s.hero_key===h.hero_key)})).sort((a,b)=>String(a.hero_name).localeCompare(String(b.hero_name),'zh-CN')))
const roles=computed(()=>[...new Set(heroes.value.map(x=>x.role).filter(Boolean))]),factionOptions=computed(()=>[...new Set(heroes.value.flatMap(x=>factions(x.faction)))]),coreHeroes=computed(()=>heroes.value.filter(x=>x.hero_core_available))
const filteredHeroes=computed(()=>{const q=heroSearch.value.toLowerCase();return heroes.value.filter(h=>(!q||[h.hero_name,h.title,h.role,h.faction,h.mechanic_summary].join(' ').toLowerCase().includes(q))&&(role.value==='all'||h.role===role.value)&&(faction.value==='all'||factions(h.faction).includes(faction.value)))})
const selectedHero=computed(()=>heroes.value.find(x=>x.hero_key===heroKey.value)||filteredHeroes.value[0]||null)
const selectedHeroes=ref([]),addHero=ref(''),teamMode=ref('total'),teamTargetDef=ref(0),teamEnemies=ref(1),teamTrials=ref(16),teamCandidates=ref(5),teamCandidatePool=ref(24),teamJob=ref(null),teamResult=ref(null),teamError=ref('')
let teamTimer=null
function isOutputHero(hero){const category=hero?.recommendation_profile?.category;if(category)return String(category).toLowerCase()==='output';return ['战士','法师','射手','fighter','mage','marksman','ranger'].includes(String(hero?.role||'').toLowerCase())}
const outputHeroes=computed(()=>heroes.value.filter(hero=>hero.hero_core_available&&isOutputHero(hero)).sort((a,b)=>String(a.hero_name||'').localeCompare(String(b.hero_name||''),'zh-CN')))
const selectedRows=computed(()=>selectedHeroes.value.map(id=>outputHeroes.value.find(hero=>hero.hero_core_id===id)).filter(Boolean))
const availableHeroes=computed(()=>outputHeroes.value.filter(hero=>!selectedHeroes.value.includes(hero.hero_core_id)))
const equipmentMap=computed(()=>new Map(equipment.value.map((row,index)=>[row.item_id,{...row,_seq:index+1}])))
async function loadHeroes(){busy.value=true;try{heroPayload.value=await api('/api/heroes');if(!heroes.value.some(x=>x.hero_key===heroKey.value))heroKey.value=heroes.value[0]?.hero_key||'';if(!recHero.value&&coreHeroes.value.length)recHero.value=coreHeroes.value[0].hero_core_id}catch(e){feedback(e)}finally{busy.value=false}}
function heroStats(h){const b=h?.base_stats||{},r=h?.resources?.rage||{};return [[zh.value?'基础攻击':'Base ATK',b.atk],[zh.value?'基础生命':'Base HP',b.hp],[zh.value?'基础防御':'Base DEF',b.def],[zh.value?'基础暴击率':'Base CRIT',b.crit_rate,'pct'],[zh.value?'基础暴伤':'Base CRIT DMG',b.crit_dmg,'pct'],[zh.value?'基础攻速':'Base ATK SPD',b.atk_speed],[zh.value?'攻击间隔':'Attack Interval',b.attack_interval,'sec'],[zh.value?'初始 / 上限怒气':'Initial / Max Rage',r.initial!=null||r.max!=null?`${n(r.initial,0)} / ${n(r.max,0)}`:null]]}
function heroStatVal(x){return x[1]===null||x[1]===undefined?'—':x[2]==='pct'?pct(x[1]):x[2]==='sec'?`${n(x[1],2)} s`:n(x[1],2)}
function downloadTemplate(){const a=document.createElement('a');a.href='/data/hero_core_template_v2.json';a.download='eaia_hero_core_template_v2.json';a.click()}
async function uploadHero(e){const f=e.target.files?.[0];e.target.value='';if(!f)return;try{const core=JSON.parse(await f.text());if(!core?.hero?.base_stats)throw new Error(zh.value?'文件必须包含 hero.base_stats。':'File must include hero.base_stats.');if(!core?.skills)throw new Error(zh.value?'文件必须包含 skills。':'File must include skills.');const r=await api('/api/hero-core/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({core})});heroKey.value=r.hero_core_id;await loadHeroes();feedback(null,zh.value?`${r.hero_name} 已导入。`:`${r.hero_name} imported.`)}catch(x){feedback(x)}}

async function loadTeamData(){try{const [h,e]=await Promise.all([api('/api/heroes'),api('/api/manage/equipment')]);heroPayload.value=h;equipment.value=(e.rows||[]).map((row,index)=>({...row,_seq:index+1}));if(!selectedHeroes.value.length&&outputHeroes.value.length>=2)selectedHeroes.value=outputHeroes.value.slice(0,2).map(hero=>hero.hero_core_id);addHero.value=availableHeroes.value[0]?.hero_core_id||''}catch(e){teamError.value=e.message}}
function addSelectedHero(){if(!addHero.value||selectedHeroes.value.includes(addHero.value))return;selectedHeroes.value.push(addHero.value);addHero.value=availableHeroes.value[0]?.hero_core_id||''}
function removeHero(index){selectedHeroes.value.splice(index,1);addHero.value=availableHeroes.value[0]?.hero_core_id||''}
function moveHero(index,delta){const next=index+delta;if(next<0||next>=selectedHeroes.value.length)return;const copy=[...selectedHeroes.value];[copy[index],copy[next]]=[copy[next],copy[index]];selectedHeroes.value=copy}
function stopTeamPoll(){if(teamTimer)clearInterval(teamTimer);teamTimer=null}
async function pollTeam(){if(!teamJob.value?.id)return;try{const state=await api('/api/hero-core/recommend/status'),fresh=(state.jobs||[]).find(job=>job.id===teamJob.value.id);if(!fresh)return;teamJob.value=fresh;if(fresh.status==='completed'){teamResult.value=fresh.result||null;stopTeamPoll()}else if(fresh.status==='failed'){teamError.value=fresh.error||'团队推荐失败';stopTeamPoll()}else if(fresh.status==='cancelled')stopTeamPoll()}catch(e){teamError.value=e.message;stopTeamPoll()}}
function startTeamPoll(){stopTeamPoll();pollTeam();teamTimer=setInterval(pollTeam,1000)}
async function runTeam(){teamError.value='';teamResult.value=null;if(selectedHeroes.value.length<2){teamError.value='团队推荐至少需要选择 2 名输出英雄。';return}try{const names=selectedRows.value.map(hero=>hero.hero_name).join(' / ');teamJob.value=await api('/api/hero-core/recommend/start',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({team:true,hero_core_ids:[...selectedHeroes.value],hero_name:`团队 · ${names}`,team_mode:teamMode.value,sets_only:setsOnly.value,target_def:Number(teamTargetDef.value),enemy_count:Number(teamEnemies.value),trials:Number(teamTrials.value),candidate_per_slot:Number(teamCandidates.value),team_candidate_pool:Number(teamCandidatePool.value),control_immune:true})});startTeamPoll()}catch(e){teamError.value=e.message}}
function teamJobLabel(status){return({queued:'排队中',starting:'准备中',screening:'候选计算中',refining:'全局分配中',completed:'已完成',failed:'失败'})[status]||status||''}
function teamFmt(value){const number=Number(value);return Number.isFinite(number)?number.toLocaleString('zh-CN',{maximumFractionDigits:0}):'—'}
function teamGearLabel(itemId,build){const row=equipmentMap.value.get(itemId),final=(build?.final_set_states||[]).find(item=>item.item_id===itemId),seq=row?`#${row._seq}`:itemId,setName=final?.set_name||row?.set_name||row?.set_id||'';return setName?`${seq} · ${setName}`:seq}
function teamSetName(build,slots){const names=[...new Set((build?.final_set_states||[]).filter(item=>slots.includes(item.slot)).map(item=>item.set_name||item.set_id))];return names.length===1?names[0]:names.join(' + ')||'—'}

// HeroCore recommendation
const recommendationMode=ref('single'),recHero=ref('SUN_WUKONG'),recPolicy=ref(''),recCore=ref(null),recDef=ref(0),recEnemies=ref(1),recTop=ref(5),recTrials=ref(32),recCandidates=ref(5),recRunning=ref(false),recPollError=ref(''),recResult=ref(null),recSort=ref({key:'rank',direction:'asc'}),recProgress=ref({status:'idle',phase:null,completed:0,total:null,overall_completed:0,overall_total:null}),recTimer=ref(null),recJobs=ref([]),recSelectedJob=ref(null),selectedBuild=ref(null)
const policies=computed(()=>Object.entries(recCore.value?.policies||{}).map(([value,x])=>({value,label:x.label||value})))
const recSelectedBusy=computed(()=>['queued','starting','screening','refining'].includes(recSelectedJob.value?.status))
const recPanelBusy=computed(()=>!recPollError.value&&(recSelectedJob.value?recSelectedBusy.value:recRunning.value))
watch(recHero,async()=>{if(!recHero.value)return;try{recCore.value=await api(`/api/hero-cores/${encodeURIComponent(recHero.value)}`);recPolicy.value=recCore.value.default_policy||policies.value[0]?.value||''}catch(e){feedback(e)}})
function stopRecPoll(){if(recTimer.value)clearInterval(recTimer.value);recTimer.value=null}
function recProgressLabel(){if(recProgress.value.status==='queued')return zh.value?'排队等待后端执行':'Waiting for backend';if(recProgress.value.phase==='screening')return zh.value?'筛选候选组合':'Screening candidate builds';if(recProgress.value.phase==='refining')return zh.value?'精算入围组合':'Refining shortlisted builds';return recProgress.value.status==='completed'?(zh.value?'计算完成':'Completed'):t('running')}
async function pollRec(){try{const statusUrl=recSelectedJob.value?.id?`/api/hero-core/recommend/status?job_id=${encodeURIComponent(recSelectedJob.value.id)}`:'/api/hero-core/recommend/status';const state=await api(statusUrl);recPollError.value='';recJobs.value=state.jobs||[];const selected=recSelectedJob.value?recJobs.value.find(x=>x.id===recSelectedJob.value.id):null;if(recSelectedJob.value){if(!selected){if(recSelectedBusy.value){recPollError.value=zh.value?'当前推荐任务已从后端队列中消失。':'The selected recommendation job is no longer available.';recRunning.value=false}return}recSelectedJob.value=selected;recProgress.value=selected;recRunning.value=recSelectedBusy.value;recResult.value=selected.status==='completed'?(selected.result||null):null;if(['completed','failed','cancelled'].includes(selected.status))stopRecPoll();return}const active=recJobs.value.find(x=>['queued','starting','screening','refining'].includes(x.status));if(active){recProgress.value=active;recRunning.value=true}else recRunning.value=false}catch(e){recPollError.value=e?.message||'Recommendation status unavailable';recRunning.value=false;feedback(e)}}
async function startRecPoll(){stopRecPoll();await pollRec();recTimer.value=setInterval(pollRec,1000);if(!recPollError.value&&!recSelectedBusy.value&&!recRunning.value)stopRecPoll()}
async function runRec(){recPollError.value='';recResult.value=null;selectedBuild.value=null;try{const hero=coreHeroes.value.find(x=>x.hero_core_id===recHero.value);const job=await api('/api/hero-core/recommend/start',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({hero_core_id:recHero.value,hero_name:hero?.hero_name||recHero.value,policy:recPolicy.value,target_def:Number(recDef.value),enemy_count:Number(recEnemies.value),top_k:Number(recTop.value),trials:Number(recTrials.value),candidate_per_slot:Number(recCandidates.value),control_immune:true})});recSelectedJob.value={...job,hero_name:hero?.hero_name||recHero.value};recProgress.value={...job,hero_name:hero?.hero_name||recHero.value};recRunning.value=true;startRecPoll()}catch(e){feedback(e)}}
function jobStatus(s){return ({queued:zh.value?'排队中':'Queued',starting:zh.value?'准备中':'Starting',screening:zh.value?'筛选中':'Screening',refining:zh.value?'精算中':'Refining',completed:zh.value?'已完成':'Completed',failed:zh.value?'失败':'Failed',cancelled:zh.value?'已删除':'Deleted'})[s]||s}
function jobProgress(job){if(job?.overall_total)return Math.min(100,Math.round(Number(job.overall_completed||0)/Number(job.overall_total)*100));return ['starting','screening','refining'].includes(job?.status)?4:0}
function focusRecResults(){requestAnimationFrame(()=>requestAnimationFrame(()=>document.querySelector('.recommendation-results')?.scrollIntoView({behavior:'smooth',block:'start'})))}
async function openRecJob(job){
  stopRecPoll();recPollError.value='';recSelectedJob.value=job;recProgress.value=job;recRunning.value=recSelectedBusy.value;selectedBuild.value=null;recResult.value=job.status==='completed'?(job.result||null):null
  if(job.status==='completed'&&!recResult.value){
    try{const state=await api(`/api/hero-core/recommend/status?job_id=${encodeURIComponent(job.id)}`),fresh=(state.jobs||[]).find(x=>x.id===job.id);if(!fresh)throw new Error(zh.value?'找不到该推荐任务。':'Recommendation job not found.');recSelectedJob.value=fresh;recProgress.value=fresh;recResult.value=fresh.result||null;recRunning.value=false}
    catch(e){recPollError.value=e?.message||'Unable to load recommendation result';feedback(e)}
  }else if(job.status==='failed'){feedback(new Error(job.error||'Recommendation failed'))}
  else if(recSelectedBusy.value){startRecPoll()}
  if(recResult.value)focusRecResults()
}
async function cancelRecJob(job){try{await api('/api/hero-core/recommend/cancel',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:job.id})});await pollRec()}catch(e){feedback(e)}}
const recResultCategory=computed(()=>String(recResult.value?.results?.[0]?.recommendation_profile?.category||'output').toLowerCase())
const recIsOutputResult=computed(()=>recResultCategory.value==='output')
function recScore(r){return recIsOutputResult.value?(r?.equivalent_60s?.mean??r?.role_score):(r?.role_score??r?.equivalent_60s?.mean)}
function recSecondaryMetric(r){const m=r?.role_metrics||{},c=recResultCategory.value;if(c==='tank')return m.defense_gain;if(c==='healing')return m.healing_effect;if(c==='support')return m.set_utility;return r?.actual_60s?.mean}
function recSecondaryLabel(){const c=recResultCategory.value;if(recIsOutputResult.value)return t('actual60');if(c==='tank')return zh.value?'防御增益':'DEF Gain';if(c==='healing')return zh.value?'治疗效果':'Healing';if(c==='support')return zh.value?'套装收益':'Set Utility';return zh.value?'角色指标':'Role Metric'}
function recSecondaryText(r){const value=recSecondaryMetric(r);if(recIsOutputResult.value)return n(value,0);return recResultCategory.value==='support'?n(value,3):pct(value)}
function recPanelStats(r){const p=r?.panel||{},m=r?.role_metrics||{},c=recResultCategory.value;if(recIsOutputResult.value)return [`ATK ${n(p.atk,0)}`,`${zh.value?'暴击':'CRIT'} ${pct(p.crit_rate)}`,`${zh.value?'暴伤':'CRIT DMG'} ${pct(p.crit_dmg)}`,`${zh.value?'攻速':'ATK SPD'} ${n(p.atk_speed,0)}`];if(c==='tank')return [`HP ${n(p.hp,0)}`,`DEF ${n(p.defense,0)}`,`${zh.value?'生命增益':'HP Gain'} ${pct(m.hp_gain)}`,`${zh.value?'防御增益':'DEF Gain'} ${pct(m.defense_gain)}`];if(c==='healing')return [`ATK ${n(p.atk,0)}`,`HP ${n(p.hp,0)}`,`${zh.value?'治疗':'Healing'} ${pct(p.healing_effect)}`,`${zh.value?'怒气':'Rage'} ${pct(p.rage_regen)}`];return [`ATK SPD ${n(p.atk_speed,0)}`,`${zh.value?'怒气':'Rage'} ${pct(p.rage_regen)}`,`HP ${n(p.hp,0)}`,`${zh.value?'套装收益':'Set Utility'} ${n(m.set_utility,3)}`]}
function recVal(r,k){return k==='ed60'?recScore(r):k==='actual'?recSecondaryMetric(r):k==='delta'?r.delta_vs_best:r[k]}
const recRows=computed(()=>{const rows=recResult.value?.results||[],s=recSort.value;return [...rows].sort((a,b)=>cmp(recVal(a,s.key),recVal(b,s.key))*(s.direction==='asc'?1:-1))})
function buildLabel(id){const x=equipment.value.find(e=>e.item_id===id);return x?`#${x._seq} · ${slotName(x)} · ${term(x.set_name)||x.set_id}`:`#${seqOf(id)}`}
function buildGear(id){return equipment.value.find(e=>e.item_id===id)||{item_id:id,stats:[]}}
function buildAscension(row,id){return(row?.upgrade_recommendations||row?.ascended_items||[]).find(x=>x.item_id===id)||null}
function buildProjection(row,id){return(row?.equipment_projection?.items||[]).find(x=>x.item_id===id)||null}
function buildFinalSet(row,id){return(row?.final_set_states||[]).find(x=>x.item_id===id)||null}
function projectedStatLabel(s){return s?statLabel({stat_type:s.stat_type,stat_value:s.projected_value}):'—'}
function projectedMainStat(row,id){return buildProjection(row,id)?.stats?.find(x=>Number(x.stat_index)===0||x.stat_source==='main')||null}
function projectedSubStats(row,id){const p=buildProjection(row,id);return(p?.stats||[]).filter(x=>Number(x.stat_index)!==0&&x.stat_source!=='main').sort((a,b)=>Number(a.stat_index)-Number(b.stat_index))}
function projectedLevel(row,id){return buildProjection(row,id)?.projected_level}
function buildFinalSetLabel(row,id){const final=buildFinalSet(row,id);return final?(term(final.set_name)||final.set_id):(term(buildGear(id).set_name)||buildGear(id).set_id||'—')}
function openBuild(row){selectedBuild.value=row}

// scanner; retains latest range/stop workflow
const device=ref({connected:false,status:'unknown',targets:[]}),scan=ref({status:'idle',completed:0,total:null,row:null,column:null,elapsed_seconds:0,average_seconds:null,new_count:0,duplicate_count:0,updated_count:0}),checking=ref(false),startRow=ref(1),startColumn=ref(1),endRow=ref(null),endColumn=ref(null);let timer=null
function scanLabel(s){const z={idle:'尚未开始',starting:'准备启动',scanning:'识别中',stopping:'正在停止',stopped:'已停止',completed:'识别完成',failed:'识别失败'},e={idle:'Idle',starting:'Starting',scanning:'Scanning',stopping:'Stopping',stopped:'Stopped',completed:'Completed',failed:'Failed'};return(zh.value?z:e)[s]||s}
async function checkDevice(){checking.value=true;try{device.value={...(await api('/api/device/check')),status:'connected'}}catch(e){device.value={connected:false,status:'failed',error:e.message,targets:[]}}finally{checking.value=false}}
function stopPoll(){if(timer)clearInterval(timer);timer=null}async function poll(){try{scan.value=await api('/api/scan/status');if(!['starting','scanning','stopping'].includes(scan.value.status))stopPoll()}catch{}}function startPoll(){stopPoll();poll();timer=setInterval(poll,1000)}
async function startScan(){const sr=Number(startRow.value),sc=Number(startColumn.value),er=Number(endRow.value),ec=Number(endColumn.value);if(!Number.isInteger(sr)||sr<1||!Number.isInteger(sc)||sc<1||sc>8||!Number.isInteger(er)||er<1||!Number.isInteger(ec)||ec<1||ec>8||((er-1)*8+ec)<((sr-1)*8+sc)){feedback(zh.value?'请输入有效的起始和终止行列，终止位置不能早于起始位置。':'Enter valid start and end positions; the end must not precede the start.');return}try{scan.value=await api('/api/scan/start',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({start_row:sr,start_column:sc,end_row:er,end_column:ec})});startPoll()}catch(e){feedback(e)}}
async function stopScan(){try{scan.value=await api('/api/scan/stop',{method:'POST'});startPoll()}catch(e){feedback(e)}}
function sec(v){if(v==null)return '—';const x=Number(v);return x<60?`${x.toFixed(1)} s`:`${Math.floor(x/60)}m ${Math.round(x%60)}s`}

async function load(v=view.value){search.value='';feedback();if(v==='dictionary')await loadDictionary();else if(v==='equipment')await loadEquipment();else if(v==='heroes')await loadHeroes();else if(v==='recommendation'){await loadTeamData();if(recHero.value){recCore.value=await api(`/api/hero-cores/${encodeURIComponent(recHero.value)}`);recPolicy.value=recCore.value.default_policy||policies.value[0]?.value||''}startRecPoll()}else if(v==='scanner'){await checkDevice();await poll()}}
watch(view,load);onMounted(async()=>{window.addEventListener('hashchange',syncHash);await loadTerms();await load()});onUnmounted(()=>{window.removeEventListener('hashchange',syncHash);stopPoll();stopRecPoll();stopTeamPoll();if(window.fetch===enhancedFetch)window.fetch=nativeFetch})
</script>

<template>
<div class="eaia-shell">
<header class="app-header"><button class="app-brand" @click="go('heroes')"><span class="brand-mark">E</span><span><strong>EAIA</strong><small>{{t('brand')}}</small></span></button><nav class="app-nav"><button v-for="x in NAV" :key="x[0]" :class="{active:x[0]===view}" @click="go(x[0])">{{x[1]}}</button></nav><div class="header-tools"><span class="local-status"><i></i>SQLite</span><button class="language-button" @click="toggleLang">{{zh?'EN':'中文'}}</button></div></header>
<main class="app-main">
<div v-if="view==='recommendation'" class="recommendation-mode page-mode-switch"><button :class="{selected:recommendationMode==='single'}" @click="recommendationMode='single'">单英雄推荐</button><button :class="{selected:recommendationMode==='team'}" @click="recommendationMode='team'">团队推荐</button></div>
<section class="page-heading"><div><p>{{view==='dictionary'?'DATA / MANAGEMENT':view==='equipment'?'EQUIPMENT / INVENTORY':view==='heroes'?'HEROES / CODEX':view==='recommendation'?'HEROCORE / BUILDS':'DEVICE / OCR'}}</p><h1>{{t(view==='dictionary'?'dictionary':view==='equipment'?'equipment':view==='heroes'?'heroes':view==='recommendation'?'recommendation':'scanner')}}</h1><span>{{view==='dictionary'?(zh?'按游戏概念组织数据，统一支持增删改与表头排序。':'Game-facing data with unified CRUD and sorting.'):view==='equipment'?(zh?'内部数据库ID隐藏，仅显示顺序序号和玩家可读属性。':'Internal database IDs are hidden; only player-facing sequence and stats are shown.'):view==='heroes'?(zh?'英雄属性、技能和 HeroCore 在同一图鉴中管理。':'Attributes, skills and HeroCore are managed in one codex.'):view==='recommendation'?(zh?'输出英雄按 HeroCore ED60 排名，防御、治疗与辅助英雄按角色目标评分排名。':'Output heroes rank by HeroCore ED60; tank, healing, and support heroes rank by role objectives.'):zh?'统一管理手机连接与识别进度。':'Unified phone connection and scan progress.'}}</span></div><div v-if="view==='heroes'" class="heading-actions"><input ref="fileInput" hidden type="file" accept="application/json,.json" @change="uploadHero"><button class="secondary-button" @click="downloadTemplate">{{t('template')}}</button><button class="primary-button" @click="fileInput?.click()">＋ {{t('upload')}}</button></div></section>
<div v-if="message" class="notice success">{{message}}</div><div v-if="error" class="notice error">{{error}}</div>

<section v-if="view==='dictionary'" class="page-grid data-grid"><aside class="side-panel"><div v-for="g in groups" :key="g.name" class="side-group"><h3>{{term(g.name)}}</h3><button v-for="x in g.items" :key="x.id" :class="{active:resourceId===x.id}" @click="loadResource(x.id)"><strong>{{term(x.title)}}</strong><small>{{x.description}}</small></button></div></aside><div class="content-panel"><div class="panel-heading"><div><p>MODULE</p><h2>{{term(resourceMeta?.title)||'—'}}</h2><span>{{resourceMeta?.description}}</span></div><button class="primary-button" @click="openResource('create')">＋ {{t('add')}}</button></div><div class="table-toolbar"><label>⌕<input v-model="search" :placeholder="t('search')"></label><span>{{resourceRows.length}}</span></div><div class="table-wrap"><div v-if="busy" class="empty-state">…</div><table v-else><thead><tr><th v-for="f in fields" :key="f.name" @click="toggleSort(resourceSort,f.name)">{{term(f.label)}} <i>{{mark(resourceSort,f.name)}}</i></th><th>{{t('actions')}}</th></tr></thead><tbody><tr v-for="(r,i) in resourceRows" :key="i"><td v-for="f in fields" :key="f.name">{{cell(r[f.name],f)}}</td><td class="row-actions"><button @click="openResource('edit',r)">{{t('edit')}}</button><button class="danger" @click="delResource(r)">{{t('del')}}</button></td></tr></tbody></table></div></div></section>

<section v-else-if="view==='equipment'" class="content-panel full-panel"><div class="panel-heading"><div><p>INVENTORY</p><h2>{{t('equipment')}}</h2><span>{{equipmentRows.length}} / {{equipment.length}}</span></div><button class="primary-button" @click="openEquipment('create')">＋ {{t('add')}}</button></div><div class="table-toolbar"><label class="equipment-search-input">⌕<input v-model="search" :placeholder="t('search')"></label><fieldset class="equipment-search-scope"><legend>{{zh?'搜索范围':'Search in'}}</legend><label v-for="option in equipmentSearchOptions" :key="option.value"><input v-model="equipmentSearchScope" type="radio" name="equipment-search-scope" :value="option.value"><span>{{option.label}}</span></label></fieldset></div><div v-if="busy" class="empty-state">{{zh?'正在加载装备数据…':'Loading equipment…'}}</div><div v-else class="table-wrap"><table><thead><tr><th @click="toggleSort(equipmentSort,'_seq')">{{t('seq')}} <i>{{mark(equipmentSort,'_seq')}}</i></th><th @click="toggleSort(equipmentSort,'slot')">{{t('slot')}} <i>{{mark(equipmentSort,'slot')}}</i></th><th @click="toggleSort(equipmentSort,'set')">{{t('set')}} <i>{{mark(equipmentSort,'set')}}</i></th><th @click="toggleSort(equipmentSort,'quality')">{{t('quality')}} <i>{{mark(equipmentSort,'quality')}}</i></th><th @click="toggleSort(equipmentSort,'enhancement_level')">{{t('level')}} <i>{{mark(equipmentSort,'enhancement_level')}}</i></th><th @click="toggleSort(equipmentSort,'main')">{{t('main')}} <i>{{mark(equipmentSort,'main')}}</i></th><th @click="toggleSort(equipmentSort,'sub')">{{t('sub')}} <i>{{mark(equipmentSort,'sub')}}</i></th><th>{{t('status')}}</th><th>{{t('actions')}}</th></tr></thead><tbody><tr v-for="r in equipmentPageRows" :key="r.item_id"><td><strong>{{r._seq}}</strong></td><td>{{slotName(r)}}</td><td>{{term(r.set_name)||r.set_id}}</td><td>{{qualityName(r)}}</td><td>+{{r.enhancement_level??0}}</td><td class="main-stat">{{statLabel(mainStat(r))}}</td><td><div class="stacked-stats"><span v-for="s in subStats(r)" :key="s.stat_index">{{statLabel(s)}}</span></div></td><td><button type="button" class="availability-button" :class="r.available?'on':'off'" @click.stop="toggleEquipmentAvailability(r)">{{r.available?(zh?'可参与配装':'Available for builds'):(zh?'不参与配装':'Excluded from builds')}}</button><span v-if="r.locked" class="status-chip lock">{{zh?'已锁定':'Locked'}}</span></td><td class="row-actions"><button @click="openEquipment('edit',r)">{{t('edit')}}</button><button class="danger" @click="delEquipment(r)">{{t('del')}}</button></td></tr></tbody></table></div><div v-if="!busy&&equipmentRows.length" class="pagination"><button class="secondary-button" :disabled="equipmentPage===1" @click="equipmentPage--">{{zh?'上一页':'Previous'}}</button><span>{{equipmentPage}} / {{equipmentPageCount}}</span><button class="secondary-button" :disabled="equipmentPage===equipmentPageCount" @click="equipmentPage++">{{zh?'下一页':'Next'}}</button></div></section>

<section v-else-if="view==='heroes'" class="hero-workspace"><div class="hero-toolbar"><label>⌕<input v-model="heroSearch" :placeholder="t('search')"></label><select v-model="role"><option value="all">{{zh?'全部职业':'All Roles'}}</option><option v-for="x in roles" :key="x" :value="x">{{term(x)}}</option></select><select v-model="faction"><option value="all">{{zh?'全部阵营':'All Factions'}}</option><option v-for="x in factionOptions" :key="x" :value="x">{{term(x)}}</option></select></div><div class="hero-layout"><div class="hero-list panel-card"><button v-for="h in filteredHeroes" :key="h.hero_key" :class="{active:selectedHero?.hero_key===h.hero_key}" @click="heroKey=h.hero_key"><span class="hero-avatar">{{h.hero_name?.slice(0,1)}}</span><span class="hero-list-text"><strong>{{term(h.hero_name)}}</strong><small>{{term(h.role)||'—'}} · {{term(h.faction)||'—'}}</small></span><i :class="h.hero_core_available?'ready':'plain'">{{h.hero_core_available?t('core'):t('nocore')}}</i></button></div><article v-if="selectedHero" class="hero-detail panel-card"><header class="hero-detail-head"><div class="hero-avatar large">{{selectedHero.hero_name?.slice(0,1)}}</div><div><p>{{selectedHero.hero_core_available?'HeroCore':'Codex'}}</p><h2>{{term(selectedHero.hero_name)}}</h2><span>{{term(selectedHero.role)||'—'}} <b v-if="selectedHero.hero_core_available">{{t('core')}}</b></span></div></header><p class="hero-summary">{{selectedHero.mechanic_summary||'—'}}</p><section><div class="section-title"><h3>{{t('attr')}}</h3></div><div class="attribute-grid"><div v-for="x in heroStats(selectedHero)" :key="x[0]"><small>{{x[0]}}</small><strong>{{heroStatVal(x)}}</strong></div></div></section><section><div class="section-title"><h3>{{t('skills')}}</h3></div><div class="skill-grid"><article v-for="s in selectedHero.skills" :key="s.skill_key"><header><span>{{s.skill_type}}</span><strong>{{term(s.skill_name)}}</strong></header><p>{{s.description||'—'}}</p><footer><span v-if="s.coefficient!=null">{{pct(s.coefficient)}}</span><span v-if="s.duration!=null">{{n(s.duration)}}s</span></footer></article></div></section><section v-if="selectedHero.talents?.length"><div class="section-title"><h3>{{t('talents')}}</h3></div><div class="skill-grid"><article v-for="x in selectedHero.talents" :key="x.id"><header><strong>{{term(x.name)}}</strong></header><p>{{x.description}}</p></article></div></section></article></div></section>

<section v-else-if="view==='recommendation'" class="recommend-layout"><aside class="config-card panel-card"><div class="panel-heading compact"><div><p>HEROCORE</p><h2>{{t('recommendation')}}</h2></div></div><label><span>{{t('heroes')}}</span><select v-model="recHero"><option v-for="h in coreHeroes" :key="h.hero_core_id" :value="h.hero_core_id">{{term(h.hero_name)}}</option></select></label><label><span>{{t('policy')}}</span><select v-model="recPolicy"><option v-for="x in policies" :key="x.value" :value="x.value">{{x.label}}</option></select></label><div class="two-cols"><label><span>{{t('targetDef')}}</span><input v-model.number="recDef" type="number" min="0"></label><label><span>{{t('enemies')}}</span><input v-model.number="recEnemies" type="number" min="1"></label></div><div class="two-cols"><label><span>{{t('topK')}}</span><input v-model.number="recTop" type="number" min="1" max="20"></label><label><span>{{t('trials')}}</span><input v-model.number="recTrials" type="number" min="1" max="256"></label></div><label><span>{{t('candidate')}}</span><input v-model.number="recCandidates" type="number" min="1" max="8"></label><button class="primary-button wide" :disabled="!coreHeroes.length" @click="runRec">{{t('run')}}</button></aside><div class="content-panel recommendation-results"><div class="panel-heading"><div><p>RESULTS</p><h2>{{t('recommendation')}}</h2><span v-if="recResult">{{recResult.combinations_screened}} {{zh?'套组合已筛选':'builds screened'}}</span></div></div><div v-if="recPanelBusy" class="empty-state">{{t('running')}}</div><div v-else-if="!recRows.length" class="empty-state">{{zh?'设置条件后开始计算。':'Configure and run the search.'}}</div><div v-else class="table-wrap"><table><thead><tr><th @click="toggleSort(recSort,'rank')"># <i>{{mark(recSort,'rank')}}</i></th><th @click="toggleSort(recSort,'ed60')">{{recIsOutputResult?t('ed60'):(zh?'角色评分':'Role Score')}} <i>{{mark(recSort,'ed60')}}</i></th><th @click="toggleSort(recSort,'actual')">{{recSecondaryLabel()}} <i>{{mark(recSort,'actual')}}</i></th><th>{{t('panel')}}</th><th>{{t('build')}}</th><th @click="toggleSort(recSort,'delta')">{{t('delta')}} <i>{{mark(recSort,'delta')}}</i></th></tr></thead><tbody><tr v-for="r in recRows" :key="r.item_ids.join('|')" class="build-result-row" @click="openBuild(r)"><td>#{{r.rank}}</td><td class="score-cell"><strong>{{n(recScore(r),recIsOutputResult?0:3)}}</strong><small v-if="recIsOutputResult">± {{n(r.equivalent_60s?.stddev??r.equivalent_60s?.std,0)}}</small><small v-else>{{zh?'角色目标综合评分':'Role objective score'}}</small></td><td>{{recSecondaryText(r)}}</td><td><div class="mini-panel"><span v-for="x in recPanelStats(r)" :key="x">{{x}}</span></div></td><td><div class="build-list"><span v-for="id in r.item_ids" :key="id">{{buildLabel(id)}}</span></div></td><td>{{pct(r.delta_vs_best)}}</td></tr></tbody></table></div></div></section>

<section v-else class="scanner-layout"><aside class="config-card panel-card"><div class="panel-heading compact"><div><p>DEVICE</p><h2>{{zh?'手机连接':'Phone Connection'}}</h2></div></div><div class="device-box" :class="device.connected?'connected':'disconnected'"><i></i><div><strong>{{device.connected?(zh?'手机已连接':'Phone Connected'):(zh?'手机未连接':'Phone Disconnected')}}</strong><small>{{device.serial||device.error||'HDC'}}</small></div></div><button class="secondary-button wide" :disabled="checking" @click="checkDevice">{{checking?'…':t('connect')}}</button><div class="scan-range"><div class="two-cols"><label><span>{{zh?'起始行':'Start Row'}}</span><input v-model.number="startRow" type="number" min="1"></label><label><span>{{zh?'起始列（1-8）':'Start Column (1-8)'}}</span><input v-model.number="startColumn" type="number" min="1" max="8"></label></div><div class="two-cols"><label><span>{{zh?'终止行':'End Row'}}</span><input v-model.number="endRow" type="number" min="0"></label><label><span>{{zh?'终止列（1-8）':'End Column (1-8)'}}</span><input v-model.number="endColumn" type="number" min="0" max="8"></label></div><p class="helper">{{zh?'终止行和列均为0表示识别到底。':'0 / 0 scans until the bottom.'}}</p></div><div class="button-row"><button class="primary-button" :disabled="!device.connected||['starting','scanning','stopping'].includes(scan.status)" @click="startScan">{{['starting','scanning','stopping'].includes(scan.status)?scanLabel(scan.status):t('start')}}</button><button class="secondary-button danger-outline" :disabled="!['starting','scanning'].includes(scan.status)" @click="stopScan">{{t('stop')}}</button></div></aside><div class="content-panel"><div class="panel-heading"><div><p>LIVE</p><h2>{{t('progress')}}</h2><span>{{scanLabel(scan.status)}}</span></div></div><div class="progress-track"><span :style="{width:`${scan.total?Math.min(100,scan.completed/scan.total*100):0}%`}"></span></div><div class="metric-grid"><div><small>{{zh?'已检测':'Scanned'}}</small><strong>{{scan.completed}} / {{scan.total??'—'}}</strong></div><div><small>{{zh?'当前位置':'Position'}}</small><strong>{{scan.row?`${scan.row} / ${scan.column}`:'—'}}</strong></div><div><small>{{zh?'已用时间':'Elapsed'}}</small><strong>{{sec(scan.elapsed_seconds)}}</strong></div><div><small>{{zh?'平均时间':'Average'}}</small><strong>{{sec(scan.average_seconds)}}</strong></div></div><div v-if="['completed','stopped'].includes(scan.status)" class="import-grid"><div><strong>{{scan.new_count}}</strong><small>{{zh?'新入库':'New'}}</small></div><div><strong>{{scan.duplicate_count}}</strong><small>{{zh?'重复':'Duplicate'}}</small></div><div><strong>{{scan.updated_count}}</strong><small>{{zh?'更新':'Updated'}}</small></div></div></div></section>
<aside v-if="view==='recommendation'" class="recommend-queue panel-card"><div class="panel-heading compact"><div><p>JOBS</p><h2>{{zh?'计算队列':'Calculation Queue'}}</h2></div><span>{{recJobs.length}}</span></div><div v-if="!recJobs.length" class="queue-empty">{{zh?'暂无计算任务':'No calculation jobs'}}</div><button v-for="job in recJobs" :key="job.id" class="queue-item" :class="{selected:recSelectedJob?.id===job.id}" @click="openRecJob(job)"><span class="queue-item-head"><strong>{{term(job.hero_name)}}</strong><em>{{jobStatus(job.status)}}</em></span><span class="queue-progress"><i :style="{width:`${jobProgress(job)}%`}"></i></span><span class="queue-item-foot"><small>{{job.status==='queued'?(zh?'等待执行':'Waiting'):job.status==='completed'?(zh?'点击查看结果':'Click to view'):job.error||`${jobProgress(job)}%`}}</small><b v-if="job.status==='queued'" @click.stop="cancelRecJob(job)">×</b></span></button></aside>

<section v-if="view==='recommendation' && recommendationMode==='team'" class="content-panel recommendation-results team-results-panel"><div class="panel-heading"><div><p>RESULTS</p><h2>团队装备推荐</h2><span v-if="teamResult?.team">{{teamResult.team_mode==='ordered'?'按序推荐':'团队总输出最高'}} · 团队 ED60 {{teamFmt(teamResult.team_total_equivalent_60s)}}</span></div></div><div v-if="teamError" class="notice error">{{teamError}}</div><div v-if="!teamResult?.team" class="empty-state">{{teamJob?'团队推荐计算中，请在右侧队列查看进度。':'选择团队英雄并开始计算。'}}</div><div v-else class="team-result team-result-light"><article v-for="hero in teamResult.heroes" :key="hero.hero_core_id"><div class="result-hero-head"><b>{{hero.priority}}</b><span><strong>{{hero.hero_name}}</strong><small>ED60 {{teamFmt(hero.equivalent_60s)}}</small></span></div><div class="result-sets"><span>左：{{teamSetName(hero.build,['weapon','armor'])}}</span><span>右：{{teamSetName(hero.build,['bracelet','necklace','ring'])}}</span></div><div class="result-items"><span v-for="itemId in hero.build.item_ids" :key="itemId">{{teamGearLabel(itemId,hero.build)}}</span></div></article></div></section>
<aside v-if="view==='recommendation' && recommendationMode==='team'" class="team-enhancement">
  <header class="team-head"><div><small>TEAM OPTIMIZER</small><strong>团队装备推荐</strong></div><span v-if="teamJob">{{teamJobLabel(teamJob.status)}}</span></header>
  <label class="set-only-switch"><input v-model="setsOnly" type="checkbox"><span><strong>仅完整套装</strong><small>同时作用于单英雄与团队；左侧必须 2 件成套，右侧必须 3 件成套。</small></span></label>
  <div class="team-mode"><button :class="{active:teamMode==='ordered'}" @click="teamMode='ordered'">按序推荐</button><button :class="{active:teamMode==='total'}" @click="teamMode='total'">总输出最高</button></div>
  <section class="hero-pick"><div class="hero-pick-title"><strong>团队英雄</strong><small>{{teamMode==='ordered'?'顺序即装备优先级':'顺序仅用于结果展示'}}</small></div><div v-for="(hero,index) in selectedRows" :key="hero.hero_core_id" class="selected-hero"><b>{{index+1}}</b><span>{{hero.hero_name}}</span><div><button :disabled="index===0" @click="moveHero(index,-1)">↑</button><button :disabled="index===selectedRows.length-1" @click="moveHero(index,1)">↓</button><button @click="removeHero(index)">×</button></div></div><div class="hero-add"><select v-model="addHero"><option value="">选择输出英雄</option><option v-for="hero in availableHeroes" :key="hero.hero_core_id" :value="hero.hero_core_id">{{hero.hero_name}}</option></select><button :disabled="!addHero" @click="addSelectedHero">添加</button></div></section>
  <div class="team-grid"><label><span>木桩防御</span><input v-model.number="teamTargetDef" type="number" min="0"></label><label><span>目标数量</span><input v-model.number="teamEnemies" type="number" min="1"></label><label><span>精算次数</span><input v-model.number="teamTrials" type="number" min="1" max="256"></label><label><span>每部位候选</span><input v-model.number="teamCandidates" type="number" min="1" max="8"></label><label v-if="teamMode==='total'" class="wide"><span>每英雄团队候选池</span><input v-model.number="teamCandidatePool" type="number" min="4" max="64"></label></div>
  <button class="run-team" :disabled="selectedHeroes.length<2||['queued','starting','screening','refining'].includes(teamJob?.status)" @click="runTeam">{{['queued','starting','screening','refining'].includes(teamJob?.status)?'团队计算中…':'计算唯一最优团队方案'}}</button><p v-if="teamError" class="team-error">{{teamError}}</p>
  <section v-if="teamResult?.team" class="team-result"><header><span>{{teamResult.team_mode==='ordered'?'按序推荐':'团队总输出最高'}}</span><strong>团队 ED60 {{teamFmt(teamResult.team_total_equivalent_60s)}}</strong><small>装备冲突 {{teamResult.equipment_conflicts}} · 共 {{teamResult.unique_item_count}} 件唯一装备</small></header><article v-for="hero in teamResult.heroes" :key="hero.hero_core_id"><div class="result-hero-head"><b>{{hero.priority}}</b><span><strong>{{hero.hero_name}}</strong><small>ED60 {{teamFmt(hero.equivalent_60s)}}</small></span></div><div class="result-sets"><span>左：{{teamSetName(hero.build,['weapon','armor'])}}</span><span>右：{{teamSetName(hero.build,['bracelet','necklace','ring'])}}</span></div><div class="result-items"><span v-for="itemId in hero.build.item_ids" :key="itemId">{{teamGearLabel(itemId,hero.build)}}</span></div></article></section>
</aside>
</main>

<div v-if="view==='recommendation' && recRunning" class="recommend-progress-float"><div class="progress-heading"><strong>{{recProgressLabel()}}</strong><span>{{recProgress.total?`${recProgress.completed} / ${recProgress.total}`:'…'}}</span></div><div class="progress-track"><span :style="{width:`${recProgress.overall_total?Math.min(100,recProgress.overall_completed/recProgress.overall_total*100):4}%`}"></span></div><small>{{recProgress.overall_total?`${Math.round(recProgress.overall_completed/recProgress.overall_total*100)}%`:''}}</small></div>

<div v-if="selectedBuild" class="modal-backdrop" @click.self="selectedBuild=null"><section class="editor-modal build-detail-modal"><header><h2>{{zh?'配装详情':'Build Details'}} #{{selectedBuild.rank}}</h2><button @click="selectedBuild=null">×</button></header><div class="build-detail-summary"><span>{{recIsOutputResult?t('ed60'):(zh?'角色评分':'Role Score')}} <strong>{{n(recScore(selectedBuild),recIsOutputResult?0:3)}}</strong></span><span v-if="recIsOutputResult">{{t('actual60')}} <strong>{{n(selectedBuild.actual_60s?.mean,0)}}</strong></span><span v-for="x in recPanelStats(selectedBuild)" :key="x"><strong>{{x}}</strong></span><span v-if="selectedBuild.equipment_projection?.locked_substat_percentile!=null">{{zh?'未解锁副词条':'Locked sub-stats'}} <strong>P{{Math.round(selectedBuild.equipment_projection.locked_substat_percentile*100)}}</strong></span><span v-if="selectedBuild.active_set_names?.length">{{zh?'最终套装':'Final Sets'}} <strong>{{selectedBuild.active_set_names.map(term).join(' + ')}}</strong></span></div><div class="detail-gear-list"><article v-for="id in selectedBuild.item_ids" :key="id"><header><strong>{{buildLabel(id)}}</strong><span>+{{buildGear(id).enhancement_level??0}}<template v-if="projectedLevel(selectedBuild,id)!=null"> → +{{projectedLevel(selectedBuild,id)}}</template></span></header><p v-if="buildAscension(selectedBuild,id)"><strong>{{zh?'建议升华':'Ascend'}}：{{term(buildAscension(selectedBuild,id).from_set_name)||buildAscension(selectedBuild,id).from_set_id}} → {{term(buildAscension(selectedBuild,id).to_set_name)||buildAscension(selectedBuild,id).to_set_id}}</strong></p><p>{{zh?'当前主词条':'Current Main Stat'}}：{{statLabel(mainStat(buildGear(id)))}}</p><p v-if="projectedMainStat(selectedBuild,id)">{{zh?'计算主词条':'Calculated Main Stat'}}：{{projectedStatLabel(projectedMainStat(selectedBuild,id))}}</p><p>{{zh?'当前副词条':'Current Sub Stats'}}：{{subStats(buildGear(id)).map(statLabel).join(' · ')||'—'}}</p><p v-if="projectedSubStats(selectedBuild,id).length">{{zh?'计算副词条':'Calculated Sub Stats'}}：{{projectedSubStats(selectedBuild,id).map(projectedStatLabel).join(' · ')}}</p><small>{{term(buildGear(id).quality_name)||buildGear(id).quality_id}} · {{zh?'计算套装':'Calculated Set'}}：{{buildFinalSetLabel(selectedBuild,id)}}<template v-if="buildProjection(selectedBuild,id)?.uses_current_main_fallback"> · {{zh?'主词条使用当前强化值':'Main stat uses current-level fallback'}}</template></small></article></div><footer><button class="secondary-button" @click="selectedBuild=null">{{zh?'关闭':'Close'}}</button></footer></section></div>

<div v-if="resourceEditor.open" class="modal-backdrop" @click.self="resourceEditor.open=false"><section class="editor-modal"><header><h2>{{resourceEditor.mode==='create'?t('add'):t('edit')}} {{term(resourceMeta?.title)}}</h2><button @click="resourceEditor.open=false">×</button></header><div class="form-grid"><label v-for="f in resource.fields" :key="f.name" :class="{wide:f.type==='textarea'}"><span>{{term(f.label)}}</span><input v-if="f.type==='text'||!f.type" v-model="resourceEditor.form[f.name]" :disabled="resourceEditor.mode==='edit'&&f.readonly_on_edit"><input v-else-if="f.type==='number'" v-model="resourceEditor.form[f.name]" type="number" step="any"><textarea v-else-if="f.type==='textarea'" v-model="resourceEditor.form[f.name]" rows="3"></textarea><label v-else-if="f.type==='boolean'" class="switch"><input v-model="resourceEditor.form[f.name]" type="checkbox"><i></i><b>{{resourceEditor.form[f.name]?(zh?'是':'Yes'):(zh?'否':'No')}}</b></label></label></div><footer><button class="secondary-button" @click="resourceEditor.open=false">{{t('cancel')}}</button><button class="primary-button" @click="saveResource">{{t('save')}}</button></footer></section></div>

<div v-if="equipmentEditor.open" class="modal-backdrop" @click.self="equipmentEditor.open=false"><section class="editor-modal equipment-editor"><header><h2>{{equipmentEditor.mode==='create'?t('add'):`${t('edit')} #${equipmentEditor.seq||'—'}`}}</h2><button @click="equipmentEditor.open=false">×</button></header><div v-if="equipmentEditor.form" class="form-grid"><label><span>{{t('slot')}}</span><select v-model="equipmentEditor.form.slot_id"><option v-for="x in slotOptions" :key="x.slot_id" :value="x.slot_id">{{pair(SLOT,x.slot_id,x.slot_name)}}</option></select></label><label><span>{{t('set')}}</span><select v-model="equipmentEditor.form.set_id"><option v-for="x in setOptions" :key="x.set_id" :value="x.set_id">{{term(x.set_name)}}</option></select></label><label><span>{{t('quality')}}</span><select v-model="equipmentEditor.form.quality_id"><option v-for="x in qualityOptions" :key="x.quality_id" :value="x.quality_id">{{pair(QUALITY,x.quality_id,x.quality_name)}}</option></select></label><label><span>{{t('level')}}</span><input v-model.number="equipmentEditor.form.enhancement_level" type="number" min="0" max="16"></label><label><span>{{zh?'可参与配装':'Available'}}</span><label class="switch"><input v-model="equipmentEditor.form.available" type="checkbox"><i></i><b>{{equipmentEditor.form.available?(zh?'是':'Yes'):(zh?'否':'No')}}</b></label></label><label><span>{{zh?'锁定':'Locked'}}</span><label class="switch"><input v-model="equipmentEditor.form.locked" type="checkbox"><i></i><b>{{equipmentEditor.form.locked?(zh?'是':'Yes'):(zh?'否':'No')}}</b></label></label><label class="wide"><span>{{zh?'备注':'Notes'}}</span><textarea v-model="equipmentEditor.form.notes" rows="2"></textarea></label></div><div v-if="equipmentEditor.form" class="stats-editor"><div class="stats-head"><strong>{{zh?'装备词条':'Equipment Stats'}}</strong><span>{{zh?'第1行为主词条，其余为副词条。':'Row 1 is main stat; others are sub stats.'}}</span></div><div v-for="(s,i) in equipmentEditor.form.stats" :key="i" class="stat-edit-row"><strong>{{i===0?t('main'):`${t('sub')} ${i}`}}</strong><select v-model="s.stat_type"><option value="">—</option><option v-for="x in statOptions" :key="x.stat_type" :value="x.stat_type">{{pair(STAT,x.stat_type,x.stat_name)}}</option></select><input v-model="s.stat_value" type="number" step="any"><select v-if="i>0" v-model="s.roll_grade_id"><option value="">—</option><option v-for="x in rollOptions" :key="x.roll_grade_id" :value="x.roll_grade_id">{{term(x.roll_grade_name)}}</option></select><span v-else></span><label class="mini-check"><input v-model="s.is_unlocked" type="checkbox">{{zh?'已解锁':'Unlocked'}}</label></div></div><footer><button class="secondary-button" @click="equipmentEditor.open=false">{{t('cancel')}}</button><button class="primary-button" @click="saveEquipment">{{t('save')}}</button></footer></section></div>
</div>
</template>

<style scoped>
.team-enhancement{position:fixed;z-index:80;right:24px;bottom:24px;width:min(420px,calc(100vw - 40px));max-height:calc(100vh - 48px);overflow:auto;padding:18px;border:1px solid rgba(120,130,150,.24);border-radius:16px;background:rgba(18,22,31,.96);color:#f6f7fb;box-shadow:0 24px 70px rgba(0,0,0,.38);backdrop-filter:blur(16px)}
.team-head,.result-hero-head,.hero-add,.selected-hero,.team-result>header{display:flex;align-items:center}.team-head{justify-content:space-between;gap:12px;margin-bottom:14px}.team-head div{display:grid;gap:2px}.team-head small,.hero-pick-title small,.set-only-switch small,.team-result small,.result-hero-head small{color:#9ca6ba}.team-head span{font-size:12px;color:#9fb7ff}.set-only-switch{display:flex;gap:10px;align-items:flex-start;padding:12px;border-radius:12px;background:rgba(255,255,255,.055);cursor:pointer}.set-only-switch input{margin-top:4px}.set-only-switch span{display:grid;gap:3px}.team-mode{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:12px 0}.team-mode button,.hero-add button,.selected-hero button{border:1px solid rgba(255,255,255,.12);border-radius:9px;background:rgba(255,255,255,.06);color:inherit;cursor:pointer}.team-mode button{padding:9px}.team-mode button.active{border-color:#7798ff;background:rgba(94,126,255,.2)}.hero-pick{display:grid;gap:7px}.hero-pick-title{display:flex;justify-content:space-between;gap:8px;align-items:baseline}.selected-hero{gap:8px;padding:7px 9px;border-radius:9px;background:rgba(255,255,255,.045)}.selected-hero>b,.result-hero-head>b{display:grid;place-items:center;width:25px;height:25px;border-radius:50%;background:rgba(119,152,255,.18)}.selected-hero>span{flex:1}.selected-hero div{display:flex;gap:4px}.selected-hero button{min-width:26px;height:26px}.selected-hero button:disabled{opacity:.3}.hero-add{gap:7px}.hero-add select,.team-grid input{min-width:0;width:100%;box-sizing:border-box;border:1px solid rgba(255,255,255,.12);border-radius:9px;background:#202632;color:#f6f7fb;padding:8px}.hero-add select{flex:1}.hero-add button{padding:8px 12px}.team-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:12px}.team-grid label{display:grid;gap:5px;font-size:12px;color:#b9c1d0}.team-grid .wide{grid-column:1/-1}.run-team{width:100%;margin-top:12px;border:0;border-radius:10px;padding:11px;font-weight:700;color:white;background:#5d7df5;cursor:pointer}.run-team:disabled{opacity:.5;cursor:default}.team-error{margin:10px 0 0;color:#ff9999;font-size:13px}.team-result{display:grid;gap:10px;margin-top:14px}.team-result>header{align-items:flex-start;flex-direction:column;gap:2px;padding-top:12px;border-top:1px solid rgba(255,255,255,.1)}.team-result article{padding:10px;border-radius:11px;background:rgba(255,255,255,.045)}.result-hero-head{gap:8px}.result-hero-head>span{display:grid;gap:1px}.result-sets{display:flex;gap:8px;margin:8px 0;font-size:12px;color:#b9c1d0}.result-items{display:grid;gap:3px;font-size:12px;color:#d8deea}
@media(max-width:720px){.team-enhancement{right:12px;bottom:12px;width:calc(100vw - 24px);max-height:70vh}}
.recommendation-mode{display:flex;gap:0;border:1px solid #d2dfe2;background:#fff;padding:3px;width:300px}.recommendation-mode button{flex:1;border:0;background:transparent;color:#74848d;padding:8px 10px;cursor:pointer;font-size:12px}.recommendation-mode button.selected{background:#e9f5f2;color:#24786f;font-weight:700}.page-mode-switch{margin-bottom:18px}.app-main:has(.page-mode-switch){display:flex;flex-direction:column}.app-main:has(.page-mode-switch)>.page-heading{order:1}.app-main:has(.page-mode-switch)>.page-mode-switch{order:2}.app-main:has(.page-mode-switch)>.recommend-layout{order:3}.team-enhancement{position:static;width:auto;max-height:none;overflow:visible;margin:0;padding:18px;background:#fff;color:#20313a;border:1px solid #dbe5e8;border-radius:0;box-shadow:0 10px 30px rgba(32,56,66,.05);backdrop-filter:none}.team-enhancement .team-head small,.team-enhancement .hero-pick-title small,.team-enhancement .set-only-switch small,.team-enhancement .team-result small,.team-enhancement .result-hero-head small{color:#81919a}.team-enhancement .team-head span{color:#278b81}.team-enhancement .set-only-switch,.team-enhancement .selected-hero,.team-enhancement .team-result article{border:1px solid #e0e8eb;border-radius:4px;background:#fbfcfc}.team-enhancement .team-mode button,.team-enhancement .hero-add button,.team-enhancement .selected-hero button{border:1px solid #d2dfe2;border-radius:4px;background:#fff;color:#52656f}.team-enhancement .team-mode button.active{border-color:#7bbab2;background:#e9f5f2;color:#24786f}.team-enhancement .hero-add select,.team-enhancement .team-grid input{border:1px solid #d5e1e4;border-radius:4px;background:#f8fafb;color:#263942}.team-enhancement .team-grid label{color:#70818a}.team-enhancement .run-team{border-radius:4px;background:#20313a}.team-enhancement .team-error{color:#a24f47}.team-enhancement .team-result>header{border-top-color:#e1e9eb}.team-enhancement .result-sets{color:#70818a}.team-enhancement .result-items{color:#52656f}.app-main:has(.team-enhancement) .recommend-layout>.config-card,.app-main:has(.team-enhancement) .recommend-layout>.recommendation-results{display:none}.app-main:has(.team-enhancement)>.team-enhancement{display:block}
@media(min-width:1051px){.app-main:has(.team-enhancement){display:grid;grid-template-columns:minmax(0,1fr) 300px;column-gap:18px}.app-main:has(.team-enhancement)>.page-heading,.app-main:has(.team-enhancement)>.notice,.app-main:has(.team-enhancement)>.page-mode-switch{grid-column:1/-1}.app-main:has(.team-enhancement)>.team-enhancement{grid-column:1;width:300px;grid-row:3}.app-main:has(.team-enhancement)>.recommend-layout{grid-column:1/-1}}
@media(max-width:1050px){.app-main:has(.team-enhancement)>.team-enhancement{margin-bottom:18px}}
.app-main:has(.team-enhancement)>.team-results-panel{display:block}.team-enhancement>.team-result{display:none}.team-result-light{display:grid!important;color:#20313a}.team-result-light article{background:#fbfcfc!important;border:1px solid #e0e8eb}.team-result-light .result-hero-head>b{background:#e8f1f2;color:#29444d}.team-result-light .result-hero-head strong{color:#263942}.team-result-light .result-hero-head small{color:#81919a}.team-result-light .result-sets{color:#70818a}.team-result-light .result-items{color:#52656f}
@media(min-width:1051px){.app-main:has(.team-enhancement)>.team-results-panel{grid-column:1/-1;grid-row:3;margin-left:318px;margin-right:302px;min-width:0}}
@media(max-width:1050px){.app-main:has(.team-enhancement)>.team-results-panel{margin:0 0 18px}}
</style>
